{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: skool-mvp-api
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "skool-mvp-api.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "skool-mvp-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: http
      path: /metrics
{{- end }}
