apiVersion: v1
kind: Service
metadata:
  name: skool-mvp-app
  namespace: apps
  labels:
    app: skool-mvp-app
spec:
  type: LoadBalancer
  selector:
    app: skool-mvp-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
