apiVersion: v1
kind: Service
metadata:
  name: skool-mvp-api
  namespace: apps
  labels:
    app: skool-mvp-api
spec:
  type: ClusterIP
  selector:
    app: skool-mvp-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
